server:
  name: Crucible
  world_id: 1
  port: 43594
  max_players: 2000
  secret_key: crucible_development
  msip: 127.0.0.1
  preload_map: false
  use_auth: false
  persist_accounts: false
  noauth_default_admin: true

paths:
  database_path: ../../db
  cache_path: ../../cache
  save_path: ../../db/players
  bot_database: ../../db/bots
  store_path: ../../db/store
  configs_path: ../../db/configs
  logs_path: ../../db/logs
  eco_database: ../../db/economy
  grand_exchange_database_path: ../../db/economy/ge
  object_parser_path: ../../db/ObjectParser.xml
  common_drop_table_path: ../../db/economy/tables/global/common.xml
  uncommon_drop_table_path: ../../db/economy/tables/global/uncommon.xml
  rare_drop_table_path: ../../db/economy/tables/global/rare.xml
  superrare_drop_table_path: ../../db/economy/tables/global/superrare.xml
  contraband_drop_table_path: ../../db/economy/tables/global/contraband.xml

database:
  database_name: global
  database_username: root
  database_password: ""
  database_address: 127.0.0.1
  database_port: 9779

world:
  name: Crucible
  debug: true
  dev: true
  start_gui: false
  daily_restart: false
  world_id: "1"
  country_id: "0"
  members: true
  activity: ""
  pvp: false
  default_xp_rate: 1.0
  motw_identifier: "0"
  motw_text: Welcome to the Crucible!
  new_player_announcement: true
  new_player_location: 2524,5002,0
  home_location: 3222,3218,0
  show_rules: true
  enable_bots: true
  enable_botting: false
  max_adv_bots: 100
  enable_default_clan: true

logging:
  file_path: ../../db/logs/server.log
  write_logs: true
  log_level: verbose
  max_file_size: 10485760
  max_files: 5
  verbose_cutscene: false

networking:
  use_ssl: false
  ssl_cert_path: ../src/main/core/api/cert.pem
  ssl_key_path: ../src/main/core/api/apikey.pem
  connectivity_check_url: https://google.com
  connectivity_timeout: 500
  daily_accounts_per_ip: 3